name: Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python library
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: python -m pytest --cov .
    - name: Upload coverage reports to Codecov
      run: |
        codecovcli create-commit
        codecovcli create-report
        codecovcli do-upload
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}